### ISSUE TITLE
compile

### ISSUE THREAD

**Issue by tkmaiti** [nake90/librcb4#1]
I compiled using following script:

gcc -L/path/to/librcb4/lib -lrcb4 -o my_program my_source.c

But, it failed. Alfonso-san suggested to use -lrcb4 at the end of the script. i.e.

gcc -L/path/to/librcb4/lib -o my_program my_source.c -lrcb4

and it compiled without error.

Thank you Alfonso-san.

**Comment by nake90** [comment]
Thanks for the bug report.

I just updated the readme file with the fixed command.
